version: 0.5.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: src\**\bin\Release\*.dll
  name: netfull
- path: src\**\bin\Release\**\*.dll
  name: netcore
deploy:
- provider: GitHub
  auth_token:
    secure: SMt+UW9Ruxn51BbZho/uvBEHmWaJ7fFFpmu0p/HTZaFdCD9z87xleqf4XgRmM6qn
  prerelease: true
  on:
    branch: master